spring:
 datasource:
   driver-class-name: org.postgresql.Driver
   url: jdbc:postgresql://192.168.1.105:54321/xyly
   username: postgres
   password: daichao1234
   #type: com.alibaba.druid.pool.DruidDataSource
   #druid:
   #       max-active: 20
   #       initial-size: 1
   #       min-idle: 3
   #       max-wait: 60000
   #       time-between-eviction-runs-millis: 60000
   #       min-evictable-idle-time-millis: 300000
   #       test-while-idle: true
   #       test-on-borrow: false
   #       test-on-return: false
   #       filters: stat,wall,log4j
 cache:
     guava:
       spec: maximumSize=500,expireAfterAccess=3600s
 jpa:
   hibernate:
    ddl-auto: update
    show-sql: true
   database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG9Dialect
 thymeleaf:
    cache: false
    # prefix: classpath:/templates
    suffix: .html
      # check-template: true # Check that the template exists before rendering it
      # check-template-location: true  # Check that the templates location exists.
      # content-type: text/html # Content-Type value.
      # enabled: true # Enable MVC Thymeleaf view resolution.
      # encoding: UTF-8 # Template encoding.
      # excluded-view-names:
      # mode: HTML5
      #
      # # Comma-separated list of view names that should be excluded from resolution. # Template mode to be applied to templates. See also StandardTemplateModeHandlers. classpath:/templates/ # Prefix that gets prepended to view names when building a URL.=.html # Suffix that gets appended to view names when building a URL.
      # template-resolver-order:  # Order of the template resolver in the chain.
      # view-names:  # Comma-separated list of view names that can be resolved.
server:
     port: 8080
     context-path: